#!/bin/sh

# This file is borrowed from openmediavault project
# WARNING: Do not edit this file, your changes will get lost.

# Setting this, so the repo does not need to be given on the commandline:
export BORG_REPO='/path/to/repo'

# Setting this, so you won't be asked for your repository passphrase:
export BORG_PASSPHRASE=''

# Temp dir in SSD
export TMPDIR='path/to/tmp/folder'

# some helpers and error handling:
info() { printf "\n%s %s\n\n" "$( date )" "$*" | tee -a ${LOG_FILE}; }
trap 'echo $( date ) Backup interrupted >&2; exit 2' INT TERM

info "Starting backup"

prefix=$1
shift

borg create \
  --verbose \
  --info \
  --stats \
  --show-rc \
  --compression auto,zstd,9 \
  --exclude-caches \
  ::"${prefix}-{now:%Y-%m-%d_%H-%M-%S}" \
  "$@" \
  2>&1 | tee -a /var/log/borgbackup.log

backup_exit=$?

sleep 1
info "Pruning repository"

borg prune \
  --list \
  --prefix "${prefix}" \
  --show-rc \
  --keep-daily 7 \
  --keep-weekly 4 \
  --keep-monthly 3 \
  2>&1 | tee -a /var/log/borgbackup.log

prune_exit=$?

# use highest exit code as global exit code
global_exit=$(( backup_exit > prune_exit ? backup_exit : prune_exit ))

if [ ${global_exit} -eq 1 ]; then
  info "Backup and/or Prune finished with a warning"
fi

if [ ${global_exit} -gt 1 ]; then
  info "Backup and/or Prune finished with an error"
fi

exit ${global_exit}
